name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
     - name: Execute start.sh
       run: |
         chmod +x ./start.sh
         ./start.sh
