name: Test Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
     - name: Execute start.sh
       run: |
         pwd
         ls -l
         # chmod +x ./start.sh
         # ./start.sh
