name: Test Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v2.1.1
    - name: Execute start.sh
      run: |
        pwd
        ls -l
        chmod +x start.sh
        ./start.sh
