name: Test Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: Execute start.sh
      run: |
        sed -i '\|logs/postgres|d' ./docker-compose.yml
        chmod +x start.sh && ./start.sh
    - name: The job has failed
      if: ${{ failure() }}
      run: |
        docker-compose config
        docker-compose logs
    - name: Newman Action
      uses: matt-ball/newman-action@0.0.28
      with:
        workingDir: test
        collection: alf-ec2.postman_collection.json
        reporters: cli,json
    - name: Postman Failed!
      if: ${{ failure() }}
      run: |
        echo "Postman Failed!"
        ls -l test
